import Head from 'next/head'
import Navbar from '@/components/Navbar';
import styles from '@/styles/Home.module.css'
import { Typography } from '@mui/material';

export default function Home() {
  return (
    <>
      <Head>
        <title>Couch Room</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <Typography>Hello, this is my personal website. We&apos;ll see what happens with it!</Typography>
      </main>
    </>
  )
}
